runtime: custom
env: flex

manual_scaling:
    instances: 1

beta_settings:
  cloud_sql_instances: metabase-271311:us-central1:metabase

env_variables:
    MB_JETTY_PORT: 8080
    MB_DB_TYPE: mysql
    MB_DB_DBNAME: metabase
    MB_DB_PORT: 3306
    MB_DB_USER: root
    MB_DB_PASS: 123456wms
    MB_DB_HOST: 127.0.0.1
